services:
  - type: web
    name: wordich-clone-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: wordich-db
          property: connectionString
      - key: WEBHOOK_URL
        value: https://wordich-clone-bot.onrender.com
      - key: PORT
        value: 8080

databases:
  - name: wordich-db
    plan: free
    databaseName: wordich
    user: wordich_user